name: test_nodejs_jobhunt
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  flutter_animate: ^4.1.1+1
  flutter_chat_bubble: ^2.0.2
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.6
  flutter_vector_icons: ^2.0.0
  flutter_zoom_drawer: ^3.0.4+1
  get: ^4.6.5
  google_fonts: ^4.0.4
  image_cropper: ^4.0.1
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  smooth_page_indicator: ^1.1.0
  socket_io_client: ^2.0.2

dev_dependencies:

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
